#' User
#'
#' @slot user_id character. ID of the user, generated by uuid
#' @slot name character. Name chosen by the user
#' @slot email character. Email of the user, must be unique
#' @slot password character. crypted password with bcrypt
#' @slot cats list. List of cats of the user
setClass("User",
         slots = c(
           user_id  = "character",
           name     = "character",
           email    = "character",
           password = "character",
           cats     = "list"
         ))


# Initialize --------------------------------------------------------------

setMethod(
  f = "initialize",
  signature = "User",
  definition = function(.Object,
                        user_id,
                        name,
                        email,
                        password,
                        cats){
    .Object@user_id  <- user_id
    .Object@name     <- name
    .Object@email    <- email
    .Object@password <- password
    .Object@cats     <- cats
    return(.Object)
  }
)







  

