#' Create new Cat
#' @include sql_requests.R
#' @import methods 
#' @importFrom uuid UUIDgenerate
#' @param db database connexion
#' @param user_id character. ID of the user, generated by uuid
#' @param body_size character. body_size of the cat, between "kitten", "small", "medium", "big"
#' @param fluffy logical. Is the cat fluffy ?
#' @param coat_pattern character. Pattern of the coat
#' @param coat_color character. Color of the coat 
#' @param eyes_color character. Eyes color of the cat
#' @param behavior character. Behavior type of the cat
#' @param comments character. Any comments of the user
#' @param seen_at time. date time when the cas is seen
#' @param lat numeric. lat of the cat
#' @param lng numeric. lng of the cat
#'
#' @return Cat
#' @export

new_cat <- function(db,
                    user_id,
                    body_size,
                    fluffy,
                    coat_pattern,
                    coat_color,
                    eyes_color,
                    behavior,
                    comments,
                    seen_at,
                    lat,
                    lng){
  
  cat_id <- uuid::UUIDgenerate()
  
  cat <- new("Cat", 
             cat_id       = cat_id,
             body_size    = body_size,
             fluffy       = fluffy,
             coat_pattern = coat_pattern,
             coat_color   = coat_color,
             eyes_color   = eyes_color,
             behavior     = behavior,
             comments     = comments,
             location     = list(new_location(db, cat_id, seen_at, lat, lng)))
  
  insert_into_cats(db = db,
                   cat_id       = cat@cat_id,
                   body_size    = cat@body_size,
                   fluffy       = cat@fluffy,
                   coat_pattern = cat@coat_pattern,
                   coat_color   = cat@coat_color,
                   eyes_color   = cat@eyes_color,
                   behavior     = cat@behavior,
                   comments     = cat@comments,
                   user_id      = user_id)
  
  return(cat)  
}