

create_table_users <- function(db){
  if (dbExistsTable(db, "users")) DBI::dbRemoveTable(db, "users")
  res <- DBI::dbSendQuery(db, 
  "CREATE TABLE users (
    user_id  TEXT PRIMARY KEY,
    name     TEXT,
    email    TEXT UNIQUE,
    password TEXT
  );"
  )
  dbClearResult(res)
  return(NULL)
}


#' Insert Into Users
#' @import DBI
#' @param db database connexion
#' @param user_id character. ID of the user, generated by uuid
#' @param name character. name chosen by the user
#' @param email character. email of the user, must not already exist in database
#' @param password character. password chosen by the user
#'
#' @return NULL
insert_into_users <- function(db, user_id, name, email, password){
  res <- DBI::dbSendQuery(db, 'INSERT INTO users (user_id, name, email, password)
                          VALUES (:user_id, :name, :email, :password)',
                          params = list(
                            user_id   = user_id,
                            name      = name, 
                            email     = email, 
                            password  = password
                          ))
  dbClearResult(res)
  return(NULL)
}


#' Select user
#' @import DBI
#' @param db database connexion
#' @param email character. ID of the cat
#'
#' @return data.frame
select_user <- function(db, email){
  res <- dbGetQuery(db, 'SELECT * FROM users WHERE  email = :email',
                    params = list(email = email))
  return(res)
}



#' Select user
#' @import DBI
#' @param db database connexion
#' @param email character. ID of the cat
#'
#' @return data.frame
exists_email <- function(db, email){
  res <- dbGetQuery(db, 'SELECT * FROM users WHERE  email = :email',
                    params = list(email = email))

  return(nrow(res)>0)
}


#' Delete user table
#' @import DBI
#' @param db database connexion
delete_table_users <- function(db){
  if (dbExistsTable(db, "users")) DBI::dbRemoveTable(db, "users")
}
